### ISSUE TITLE
[TYPO] typo in week 1 lecture

### ISSUE THREAD

**Issue by JacksonBurns** [JacksonBurns/MATLAB-Start-to-Finish#4]
File where you found the typo:
week 1 lecture
Header, Section, and/or Line where you found the typo:
MATLAB Syntax, 3rd bullet point
Correction:
MTALAB->MATLAB

**Comment by 96RadhikaJadhav** [comment]
@JacksonBurns Can I work on the issue?

**Comment by JacksonBurns** [comment]
Sure @96RadhikaJadhav, see my comment in #7

**Comment by JacksonBurns** [comment]
Resolved in #11
