### ISSUE TITLE
[TYPO] week 2 lecture

### ISSUE THREAD

**Issue by JacksonBurns** [JacksonBurns/MATLAB-Start-to-Finish#5]
File where you found the typo:
week 2 lecture
Header, Section, and/or Line where you found the typo:
plotting functions, under second example
Correction:
Linscpace -> Linspace

**Comment by 96RadhikaJadhav** [comment]
@JacksonBurns  Can I work on the issue?

**Comment by JacksonBurns** [comment]
Sure @96RadhikaJadhav, see my comment in #7

**Comment by JacksonBurns** [comment]
Resolved in #11
