### ISSUE TITLE
[TYPO] week 2 lecture

### ISSUE THREAD

**Issue by JacksonBurns** [JacksonBurns/MATLAB-Start-to-Finish#6]
File where you found the typo:
week 2 lecture
Header, Section, and/or Line where you found the typo:
General Plot Customizing functions
Correction:
 MATLAB will inherently call gcf (get current figure documentation and operate -> I don't know what this should be set to, I think this might be a Markdown error.

**Comment by 96RadhikaJadhav** [comment]
@JacksonBurns  How about setting the above line to - "MATLAB will inherently call gcf, which is not a variable but rather a function. Whenever you call it, it will retrieve whichever is the current figure. gcf returns the current figure handle. If a figure does not exist, then gcf creates a figure and returns its handle. You can use the figure handle to query and modify figure properties."

Or if you suggest anything else I will make that change.

**Comment by JacksonBurns** [comment]
The above sounds good @96RadhikaJadhav, please add a link to the documentation for **gcf** as well.

**Comment by 96RadhikaJadhav** [comment]
@JacksonBurns  The link for documentation is already there. I won't remove that.  Will adjust the link here in paragraph only. Sounds good?

**Comment by JacksonBurns** [comment]
resolved with #12
