### ISSUE TITLE
[TYPO] week 5 lecture heading

### ISSUE THREAD

**Issue by JacksonBurns** [JacksonBurns/MATLAB-Start-to-Finish#7]
File where you found the typo:
week 5 lecture
Header, Section, and/or Line where you found the typo:
Pseudocode - stdying the workflow
Correction:
stdying -> studying

**Comment by 96RadhikaJadhav** [comment]
@JacksonBurns  Can I work on the issue?

**Comment by JacksonBurns** [comment]
Sure @96RadhikaJadhav, go ahead and fork the repository and then open a pull request with your changes!

**Comment by JacksonBurns** [comment]
Resolved in #11
